"""Patch meta_path_library.py to include auto-generated paths."""
import re

lib_path = "C:/Users/vishnu/.openclaw/workspace/SAP_HANA_LLM_VendorChatbot/backend/app/core/meta_path_library.py"

with open(lib_path, encoding="utf-8") as f:
    content = f.read()

# Find the singleton line
old_block = "# Singleton\nmeta_path_library = MetaPathLibrary(SAP_META_PATHS)"

new_block = """# ── Auto-Generated Paths (from graph traversal) ──────────────────────────────
# Generated by: meta_path_auto_generator_v2.py
try:
    from app.core.sql_patterns.auto_meta_paths_v2 import AUTO_META_PATHS_V2
    _auto_converted = []
    for d in AUTO_META_PATHS_V2:
        _join_tuples = []
        for _entry in d.get('join_conditions', []):
            if isinstance(_entry, (list, tuple)) and len(_entry) == 3:
                _t1, _t2, _cond = _entry
                if isinstance(_cond, str):
                    _join_tuples.append((_t1, _t2, _cond))
        _variants = [PathVariant(
            tables=d['tables'],
            join_conditions=_join_tuples,
            cardinality_notes='',
            score=0.8,
            bloom_filter=d.get('tags', [])
        )] if _join_tuples else [PathVariant(
            tables=d['tables'],
            join_conditions=[],
            cardinality_notes='',
            score=1.0,
            bloom_filter=d.get('tags', [])
        )]
        _auto_converted.append(MetaPath(
            id=d['id'],
            name=d['name'],
            business_description=d['business_description'],
            domain=d.get('domain', 'auto_generated'),
            module=d.get('module_pair', d.get('module', 'AUTO')),
            tags=d.get('tags', []),
            variants=_variants,
            required_filters=d.get('required_filters', ['MANDT = :P_MANDT']),
            optional_filters=d.get('optional_filters', []),
            sql_template=d['sql_template'],
            select_columns={t: d['tables'] for t in d['tables']},
            example_queries=d.get('example_queries', []),
            confidence_boost=d.get('confidence_boost', 0.15),
            row_count_warning=d.get('row_count_warning', ''),
        ))
    SAP_META_PATHS.extend(_auto_converted)
    print(f"[META-PATH] Loaded {len(_auto_converted)} auto paths. Total: {len(SAP_META_PATHS)}")
except Exception as e:
    print(f"[META-PATH] Auto-paths skipped: {e}")

# Singleton
meta_path_library = MetaPathLibrary(SAP_META_PATHS)"""

if old_block in content:
    content = content.replace(old_block, new_block)
    with open(lib_path, "w", encoding="utf-8") as f:
        f.write(content)
    print("Patched successfully.")
else:
    print("Could not find singleton marker. Content around line 1929:")
    lines = content.split('\n')
    for i, line in enumerate(lines[1925:1935], 1926):
        print(f"  {i}: {repr(line)}")
